language: android
jdk: oraclejdk8
dist: trusty
os: linux
cache: false # Turn off caching to prevent any caching problems
sudo: false # Use Travis Container-Based Infrastructure (faster builds)

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - ANDROID_EMU_API_LEVEL=22
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8 # 8 minute timeout to prevent unresponsive shell error
    - QEMU_AUDIO_DRV=none # Remove audio

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMU_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  # To add new encrypted files: travis encrypt-file secrets.xml secrets.xml.enc -r CMPUT301F20T15/BookwormAdventuresDeluxe2 --com
  - openssl aes-256-cbc -K $encrypted_3d990a7f02ba_key -iv $encrypted_3d990a7f02ba_iv -in travis_secrets/secrets.xml.enc -out app/src/main/res/values/secrets.xml -d
  - yes | sdkmanager "platforms;android-$ANDROID_EMU_API_LEVEL"
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

before_script:
  - chmod +x gradlew
  # Start the emulator
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
